name: Count Lines of README

on:
  push:
    branches:
      - main

jobs:
  count_lines:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Count lines of README
      run: |
        README_PATH="/PabloTaber/CodeWars/README.md"
        line_count=$(wc -l < "${GITHUB_WORKSPACE}${README_PATH}")
        echo "El número de líneas en $README_PATH es: $line_count"
